server:
  port: 8000
spring:
  thymeleaf:
    cache: false

  application:
    name: web-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://45.77.250.207:8005/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#rocketmq:
#  name-server: 45.77.250.207:9876
#  producer:
#    group: miaosha
