server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha_vua
    #type: org.apache.tomcat.jdbc.pool.DataSource
    #type: com.zaxxer.hikari.HikariDataSource #default
    #type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 841103
  application:
    name: product-service
  redis:
    password: 841103
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://45.77.250.207:8005/eureka/
  instance:
    prefer-ip-address: true
rocketmq:
  name-server: 45.77.250.207:9876